name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=cobertura /p:Threshold=80 /p:ThresholdType=line /p:ThresholdStat=total
    - name: Install ReportGenerator
      run: dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools
    - name: Run ReportGenerator
      run: .\tools\reportgenerator.exe -reports:.\TestResults\coverage.cobertura.xml -targetdir:.\TestResults\

