name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=cobertura /p:Threshold=80 /p:ThresholdType=line /p:ThresholdStat=total
    - name: Install Report Generator
      run: dotnet tool install dotnet-reportgenerator-globaltool --tool-path /home/runner/work/Coverlet22WebApp/Coverlet22WebApp/Coverlet22WebApp.UnitTest/tools
    - name: Run Report Generator
      run: /home/runner/work/Coverlet22WebApp/Coverlet22WebApp/Coverlet22WebApp.UnitTest/tools/reportgenerator.exe -reports:/home/runner/work/Coverlet22WebApp/Coverlet22WebApp/Coverlet22WebApp.UnitTest/TestResults/coverage.cobertura.xml -targetdir:/home/runner/work/Coverlet22WebApp/Coverlet22WebApp/Coverlet22WebApp.UnitTest/TestResults/
    - uses: actions/upload-artifact@v1
      with:
        name: Coverage Results
        path: /home/runner/work/Coverlet22WebApp/Coverlet22WebApp/Coverlet22WebApp.UnitTest/TestResults/

